#配置第一个用户微服务
server:
  #服务端口
  port: 8191
spring:
  #区分不同环境下的配置文件
  profiles: user1
management:
  server:
    port: 8191
  endpoints:
    web:
      base-path: /actuator #默认是/actuator 前缀，可以在这里修改
      exposure:
        include: "*"

---
#配置第二个用户微服务
server:
  #服务端口
  port: 8192
spring:
  #区分不同环境下的配置文件
  profiles: user2

management:
  server:
    port: 8192
  endpoints:
    web:
      base-path: /actuator #默认是/actuator 前缀，可以在这里修改
      exposure:
        include: "*"



