server:
  port: 8181

spring:
  application:
    name: config-server
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8769
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xia-deng/config-manager
          username: XXXXXXXXXXXX
          password: XXXXXXXXXXX
          default-label: master
          search-paths: /
          force-pull: true

#±æµÿ≈‰÷√‘¥#
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:config/
#  profiles:
#    active: native
#                    native:
#                      search-locations: classpath:config/
debug: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS